### ISSUE TITLE
Error opening .fb2

### ISSUE THREAD

**Issue by Korb** [btpf/Alexandria#54] opened 2024-10-06 06:29 UTC
```
Unhandled Thrown Error!
Cannot read properties of undefined (reading'0')
TypeError: Cannot read properties of undefined (reading '0')
at compare (https://tauri.localhost/bundle.js:172:63502)
at Am (https://tauri.localhost/bundle.js:172:53456)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
at Am (https://tauri.localhost/bundle.js:172:53513)
Hey developer
You can provide a way better UX than this when your app throws errors by providing your
own error Element
props on <Route>
```

SumatraPDF v3.5.2 64-bit — OK.

Alexandria_0.12.0_x64-portable.exe
Microsoft Windows 10.0.19045.4957
[Alexandria test.fb2](https://drive.google.com/file/d/1IZNQ9Fknb2lcI8MB3jWXhNvxmfzNrcOR/view)

**Comment by btpf** [comment] 2024-10-06 20:11
Duplicate of https://github.com/btpf/Alexandria/issues/47

**Closed by btpf** 2024-10-06 20:11 UTC
