### ISSUE TITLE
Crashes on launch on windows 10.

### ISSUE THREAD

**Issue by cougarten** [btpf/Alexandria#3] opened 2023-08-29 07:10 UTC
Any logs or something I could provide?

I see the logo briefly in the taskbar before the app is gone again, no window to be seen.

**Comment by btpf** [comment] 2023-08-29 14:07
Hi, I currently don't have any log files. But maybe we can find more information from the event viewer for the time being.
Can you post them here? Thanks.

Here is a video guide in case you need it.
https://www.youtube.com/watch?v=TMpLx3SXuNk

**Comment by cougarten** [comment] 2023-08-29 16:05
thanks for the reply!
nothing in the event viewer (win logs > apps) :/

**Comment by djordje-zivkovic** [comment] 2023-08-29 22:04
Same problem, it installs, but then just briefly see icon. Reinstall didn't fix. Also no logs.

**Comment by btpf** [comment] 2023-09-01 02:06
I am able to reproduce the issue. While I work on resolving this, feel free to use the portable version of the app which doesn't have this problem.

**Closed** 2023-09-01 04:50 UTC

**Comment by btpf** [comment] 2023-09-01 05:24
I didn't realize github automatically closed issues when they are referenced in a commit.
Please try https://github.com/btpf/Alexandria/releases/tag/0.9.2 and tell me if the problem is still there. Thanks.

**Comment by djordje-zivkovic** [comment] 2023-09-01 08:15
With 0.9.2 I'm able to successfully launch the application. Thank you @btpf

**Comment by cougarten** [comment] 2023-09-02 09:34
can confirm! :) thanks!

**Comment by forswearadidas** [comment] 2023-12-28 19:54
I am having the same issue with latest (0.11.2version) in windows 10 pro 22h2
Used the latest setup and msi installer and portable version all crashes on start of application
